Proyecto/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Proyecto.Models
{
    public class Usuario
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string Description { get; set; }
        public int Weight { get; set; }
        public int Height { get; set; }
        public string Activity { get; set; }

        public int IdDieta { get; set; }
        [ForeignKey("IdDieta")]
        public Dieta? Dieta { get; set; }
        public int TotalCalories { get; set; }

    }
}

Proyecto/Controllers/DietasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto.Data;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class DietasController : Controller
    {
        private readonly ProyectoContext _context;

        public DietasController(ProyectoContext context)
        {
            _context = context;
        }

        // GET: Dietas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Dieta.ToListAsync());
        }

        // GET: Dietas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dieta = await _context.Dieta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dieta == null)
            {
                return NotFound();
            }

            return View(dieta);
        }

        // GET: Dietas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dietas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameDiet,DescriptionDiet,Calories,Proteins,Carbohydrates,DietType")] Dieta dieta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dieta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dieta);
        }

        // GET: Dietas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dieta = await _context.Dieta.FindAsync(id);
            if (dieta == null)
            {
                return NotFound();
            }
            return View(dieta);
        }

        // POST: Dietas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameDiet,DescriptionDiet,Calories,Proteins,Carbohydrates,DietType")] Dieta dieta)
        {
            if (id != dieta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dieta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DietaExists(dieta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dieta);
        }

        // GET: Dietas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dieta = await _context.Dieta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dieta == null)
            {
                return NotFound();
            }

            return View(dieta);
        }

        // POST: Dietas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dieta = await _context.Dieta.FindAsync(id);
            if (dieta != null)
            {
                _context.Dieta.Remove(dieta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DietaExists(int id)
        {
            return _context.Dieta.Any(e => e.Id == id);
        }

        // POST: Mostrar dieta según calorías del usuario
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MostrarDietaSegunCalorias(string idUsuario)
        {
            var usuario = await _context.Usuario.FindAsync(idUsuario);

            if (usuario == null)
            {
                return NotFound();
            }

            int calorias = usuario.TotalCalories;

            if (calorias < 2000)
            {
                return RedirectToAction("DietaBaja", new { id = usuario.Id });
            }
            else if (calorias < 3000)
            {
                return RedirectToAction("DietaMedia", new { id = usuario.Id });

            }
            else
            {
                return RedirectToAction("DietaAlta", new { id = usuario.Id });
            }
        }

        // Vistas de dietas personalizadas según calorías
        public async Task<IActionResult> DietaBaja(string id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null) return NotFound();
            return View("DietaBaja", usuario);
        }

        public async Task<IActionResult> DietaMedia(string id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null) return NotFound();
            return View("DietaMedia", usuario);
        }

        public async Task<IActionResult> DietaAlta(string id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null) return NotFound();
            return View("DietaAlta", usuario);
        }
    }
}

Proyecto/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto.Data;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ProyectoContext _context;

        public UsuariosController(ProyectoContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            var proyectoContext = _context.Usuario.Include(u => u.Dieta);
            return View(await proyectoContext.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .Include(u => u.Dieta)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            ViewData["IdDieta"] = new SelectList(_context.Dieta, "Id", "Id");
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Sex,Age,Description,Weight,Height,Activity,IdDieta")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                // Calcular TMB
                double tmb;
                if (usuario.Sex == "Mujer")
                {
                    tmb = 10 * usuario.Weight + 6.25 * usuario.Height - 5 * usuario.Age + 5;
                }
                else
                {
                    tmb = 10 * usuario.Weight + 6.25 * usuario.Height - 5 * usuario.Age - 161;
                }

                double factorActividad = usuario.Activity switch
                {
                    "Baja" => 1.2,
                    "Moderada" => 1.55,
                    "Alta" => 1.9,
                    _ => 1.2
                };

                usuario.TotalCalories = (int)(tmb * factorActividad);

                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdDieta"] = new SelectList(_context.Dieta, "Id", "Id", usuario.IdDieta);
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["IdDieta"] = new SelectList(_context.Dieta, "Id", "Id", usuario.IdDieta);
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Sex,Age,Description,Weight,Height,Activity,IdDieta,TotalCalories")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDieta"] = new SelectList(_context.Dieta, "Id", "Id", usuario.IdDieta);
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .Include(u => u.Dieta)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(string id)
        {
            return _context.Usuario.Any(e => e.Id == id);
        }
    }
}

Proyecto/Views/Usuarios/Create.cshtml
@model Proyecto.Models.Usuario

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear usuario</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Id" class="control-label">ID</label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label">Nombre</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Sex" class="control-label">Género</label>
                <select asp-for="Sex" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                </select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label">Edad (años)</label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label">Objetivo</label>
                <input asp-for="Description" class="form-control" placeholder="Por ejemplo: Perder peso" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Weight" class="control-label">Peso (kg)</label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Height" class="control-label">Altura (cm)</label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Activity" class="control-label">Nivel de actividad</label>
                <select asp-for="Activity" class="form-control">
                    <option value="Baja">Baja (actividad mínima)</option>
                    <option value="Moderada">Moderada (3-5 veces/semana)</option>
                    <option value="Alta">Alta (6-7 veces/semana)</option>
                </select>
                <span asp-validation-for="Activity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdDieta" class="control-label">Dieta</label>
                <select asp-for="IdDieta" class="form-control" asp-items="ViewBag.IdDieta"></select>
            </div>

            <input type="hidden" asp-for="TotalCalories" value="0" />

            <div class="form-group mt-3">
                <input type="submit" value="Calcular" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto/Views/Usuarios/Delete.cshtml
@model Proyecto.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dieta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dieta.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCalories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalCalories)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Proyecto/Views/Usuarios/Details.cshtml
@model Proyecto.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dieta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dieta.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCalories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalCalories)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Proyecto/Views/Usuarios/Edit.cshtml
@model Proyecto.Models.Usuario

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar usuario</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label">Nombre</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Sex" class="control-label">Género</label>
                <select asp-for="Sex" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                </select>
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label">Edad (años)</label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label">Objetivo</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Weight" class="control-label">Peso (kg)</label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Height" class="control-label">Altura (cm)</label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Activity" class="control-label">Nivel de actividad</label>
                <select asp-for="Activity" class="form-control">
                    <option value="Baja">Baja</option>
                    <option value="Moderada">Moderada</option>
                    <option value="Alta">Alta</option>
                </select>
                <span asp-validation-for="Activity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdDieta" class="control-label">Dieta</label>
                <select asp-for="IdDieta" class="form-control" asp-items="ViewBag.IdDieta"></select>
                <span asp-validation-for="IdDieta" class="text-danger"></span>
            </div>

            @* No mostramos el campo TotalCalories pero sigue presente en el modelo *@
            <input type="hidden" asp-for="TotalCalories" />

            <div class="form-group mt-3">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto/Views/Usuarios/Index.cshtml
@model IEnumerable<Proyecto.Models.Usuario>

@{
    ViewData["Title"] = "Tabla de Usuarios";
}

<h1>Tabla de Usuarios</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear Nuevo</a>
</p>

<table class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
                <span class="badge badge-info">Nombre</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
                <span class="badge badge-info">Sexo</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
                <span class="badge badge-info">Edad</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
                <span class="badge badge-info">Descripción</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
                <span class="badge badge-info">Peso</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
                <span class="badge badge-info">Altura</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activity)
                <span class="badge badge-info">Actividad</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dieta)
                <span class="badge badge-info">Dieta</span>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCalories)
                <span class="badge badge-info">Calorías Totales</span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sex)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Activity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dieta.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalCalories)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Editar</a> |
                    <form asp-controller="Dietas" asp-action="MostrarDietaSegunCalorias" method="post" style="display:inline;">
                        <input type="hidden" name="idUsuario" value="@item.Id" />
                        <button type="submit" class="btn btn-sm btn-info">Ver Dieta</button>
                    </form> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>